### ISSUE TITLE
Issue with Ubuntu 22.04 duee to libssl-dev version

### ISSUE THREAD

**Issue by trunksio** [memgraph/pymgclient#50]
When using ubuntu 22.04 and installing gqlalchemy with python 3.10 I get the following error:

>>> from gqlalchemy import memgraph
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/lewis/miniconda3/envs/gql/lib/python3.10/site-packages/gqlalchemy/__init__.py", line 34, in <module>
    from gqlalchemy.instance_runner import (  # noqa F401
  File "/home/lewis/miniconda3/envs/gql/lib/python3.10/site-packages/gqlalchemy/instance_runner.py", line 31, in <module>
    from gqlalchemy.vendors.memgraph import Memgraph
  File "/home/lewis/miniconda3/envs/gql/lib/python3.10/site-packages/gqlalchemy/vendors/memgraph.py", line 19, in <module>
    from gqlalchemy.connection import Connection, MemgraphConnection
  File "/home/lewis/miniconda3/envs/gql/lib/python3.10/site-packages/gqlalchemy/connection.py", line 18, in <module>
    import mgclient
ImportError: /home/lewis/miniconda3/envs/gql/lib/python3.10/site-packages/mgclient.cpython-310-x86_64-linux-gnu.so: undefined symbol: SSL_get1_peer_certificate

**Comment by antaljanosbenjamin** [comment]
I think this issue arises because of the miniconda environment (which ships its own OpenSSL version) not with Ubuntu 22.04. Unfortunately I am not aware of any solution that makes binary packages compatible with different OpenSSL library versions.

However there is a solution: [install pymgclient from source](https://memgraph.github.io/pymgclient/introduction.html#install-from-source). The documentation is a bit out of date, pymgclient supports OpenSSL 3, so there shouldn't be any issues. To be sure it uses the correct OpenSSL version, try to specify the environment variable `OPENSSL_ROOT_DIR` to point to the root of the miniconda environment, probably `$HOME/miniconda3` should work.

Can you please try this?

**Comment by trunksio** [comment]
Hi - after many attempts I have abandoned miniconda and used the ubuntu python 3.10 packages and this is working for me now.
